// Spec -> source. Three outputs, off one spec so none can lag the others:
//
//   endpoints.ts   — the callable client, one `op()` per operation
//   operations.ts  — a named request/response type per operation, plus one
//                    named type per component schema (`CourseOut`, `Token`)
//   api.md         — every path, verb, request and response, for reading

const VERBS = ["get", "post", "put", "patch", "delete"];

// `#/components/schemas/MemberOut` -> `MemberOut`, which is the key to look up
// in schema.ts. Inline shapes have no name, so they get their JSON type.
const name = (schema) => {
  if (!schema) return "—";
  if (schema.$ref) return `\`${schema.$ref.split("/").pop()}\``;
  if (schema.items) return `${name(schema.items)}[]`;
  if (schema.anyOf) return schema.anyOf.map(name).join(" \\| ");
  return `\`${schema.type ?? "object"}\``;
};

const json = (body) => name(body?.content?.["application/json"]?.schema);

// The first path segment after the prefix: `members` for `/api/v1/members/{id}`
// under `/api/v1`. A path outside the prefix keeps its own first segment, so
// `/healthz` still groups under `healthz` rather than standing alone.
const groupOf = (path, prefix) =>
  (path.startsWith(`${prefix}/`) ? path.slice(prefix.length + 1) : path)
    .split("/")
    .filter(Boolean)[0] ?? path;

export function operations(spec, { prefix = "" } = {}) {
  const rows = [];
  for (const [path, item] of Object.entries(spec.paths ?? {})) {
    for (const verb of VERBS) {
      const op = item[verb];
      if (!op) continue;

      const status = Object.keys(op.responses).find((c) => c.startsWith("2"));
      const params = [...(item.parameters ?? []), ...(op.parameters ?? [])];
      const query = params
        .filter((p) => p.in === "query")
        .map((p) => `${p.name}${p.required ? "" : "?"}`)
        .join(", ");

      rows.push({
        group: groupOf(path, prefix),
        path,
        verb: verb.toUpperCase(),
        query: query || "—",
        req: json(op.requestBody),
        res: status === "204" ? "—" : json(op.responses[status]),
        status,
      });
    }
  }
  return rows;
}

export function renderDocs(spec, { prefix = "" } = {}) {
  const rows = operations(spec, { prefix });
  const groups = [...new Set(rows.map((r) => r.group))];
  return [
    "<!-- Generated by openapi-op — `npm run codegen` rewrites this. -->",
    "",
    "# API map",
    "",
    `${spec.info?.title ?? "API"} ${spec.info?.version ?? ""} — ${rows.length} operations.`,
    "Type names are keys of `components[\"schemas\"]` in `schema.ts`;",
    'reach them by name from `operations.ts` (e.g. `import type { MemberOut } from "@/lib/operations"`).',
    "",
    ...groups.flatMap((g) => [
      `## ${g}`,
      "",
      "| Method | Path | Query | Request | → | Response |",
      "| --- | --- | --- | --- | --- | --- |",
      ...rows
        .filter((r) => r.group === g)
        .map((r) => `| ${r.verb} | \`${r.path}\` | ${r.query} | ${r.req} | ${r.status} | ${r.res} |`),
      "",
    ]),
  ].join("\n");
}

// --- endpoints.ts ---

const camel = (s) =>
  s
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((w, i) => (i ? w[0].toUpperCase() + w.slice(1).toLowerCase() : w.toLowerCase()))
    .join("");

// `List Members` in the `members` group is `members.list`, not
// `members.listMembers` — the group already said it. Only the trailing word
// goes, and only when it *is* the group, so `changeRole` under members keeps
// its noun.
function methodName(summary, group) {
  const words = summary.trim().split(/\s+/);
  const last = words.at(-1).toLowerCase().replace(/s$/, "");
  if (words.length > 1 && last === group.toLowerCase().replace(/s$/, "")) words.pop();
  return camel(words.join(" "));
}

export function endpoints(spec, { prefix = "" } = {}) {
  const groups = new Map();

  for (const [path, item] of Object.entries(spec.paths ?? {})) {
    // The generated client only speaks to routes under the prefix `api()`
    // adds — anything outside it (/healthz) is left to a direct call.
    if (!path.startsWith(`${prefix}/`)) continue;
    const group = groupOf(path, prefix);

    for (const verb of VERBS) {
      const operation = item[verb];
      if (!operation) continue;

      const rows = groups.get(group) ?? [];
      const status = Object.keys(operation.responses).find((c) => c.startsWith("2"));
      const res = operation.responses[status]?.content?.["application/json"]?.schema?.$ref;

      let key = methodName(operation.summary ?? `${verb} ${group}`, group);
      // A summary that collides after the group word is dropped keeps its verb.
      if (rows.some((r) => r.key === key)) key = camel(`${verb} ${key}`);

      rows.push({
        key,
        path,
        verb,
        doc: [operation.summary, operation.description].filter(Boolean).join("\n\n"),
        // A `Paginated[X]` response also gets a rows-only sibling — every
        // caller today wants `.items`, and the envelope stays one call away.
        paginated: (res ?? "").split("/").pop()?.startsWith("Paginated_") ?? false,
      });
      groups.set(group, rows);
    }
  }
  return groups;
}

const jsdoc = (text, indent) =>
  text
    ? [
      `${indent}/**`,
      ...text.split("\n").map((l) => `${indent} *${l ? ` ${l.trimEnd()}` : ""}`),
      `${indent} */`,
    ]
    : [];

export function renderEndpoints(spec, { prefix = "", client = "./api" } = {}) {
  const groups = endpoints(spec, { prefix });
  const out = [
    "// GENERATED by openapi-op — `npm run codegen` rewrites this file.",
    "// Do not edit: every name, path, verb and doc comment comes from the spec.",
    "//",
    `// Each entry is \`op(path, verb)\` from ${client}, which reads the request,`,
    "// query, path params and response type out of schema.ts.",
    "",
    `import { op } from "${client}";`,
    "",
  ];

  for (const [group, rows] of groups) {
    // A paginated op is hoisted to a const first: the `Items` sibling refers to
    // it, and a reference to the object being defined is circular.
    const hoisted = (row) => camel(`${group} ${row.key}`);
    for (const row of rows.filter((r) => r.paginated)) {
      out.push(`const ${hoisted(row)} = op("${row.path}", "${row.verb}");`);
    }

    out.push(`export const ${camel(group)} = {`);
    for (const row of rows) {
      out.push(...jsdoc(row.doc, "  "));
      out.push(
        row.paginated
          ? `  ${row.key}: ${hoisted(row)},`
          : `  ${row.key}: op("${row.path}", "${row.verb}"),`,
      );
      if (row.paginated) {
        out.push(
          `  /** \`${row.key}\`, unwrapped to the rows — the envelope carries \`total\` and \`next_offset\`. */`,
          `  ${row.key}Items: async (...args: Parameters<typeof ${hoisted(row)}>) =>`,
          `    (await ${hoisted(row)}(...args)).items,`,
        );
      }
    }
    out.push("};", "");
  }
  return out.join("\n");
}

// --- operations.ts ---

// `Change Role` -> `ChangeRole`. Unlike `camel`, the rest of each word is left
// alone, so an acronym in a summary (`IELTS Item`) survives as one.
const pascal = (s) =>
  s
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join("");

export function operationTypes(spec) {
  const rows = [];
  const taken = new Set();
  // A base whose `…Request`/`…Response` would shadow a component schema of
  // that exact name (`Checkout` the plan flow vs. `CheckoutRequest` the
  // schema) collides just as much as two operations would — both land in
  // `operations.ts` as an `export type` of the same name.
  const modelNames = new Set(modelTypes(spec));

  for (const [path, item] of Object.entries(spec.paths ?? {})) {
    for (const verb of VERBS) {
      const op = item[verb];
      if (!op) continue;

      // The summary is the name the spec already chose — the same string
      // `endpoints.ts` turns into a method, so the type beside a call reads
      // like the call. Two summaries that collide keep their verb apart.
      let base = pascal(op.summary || `${verb} ${path}`);
      if (taken.has(base) || modelNames.has(`${base}Request`) || modelNames.has(`${base}Response`)) {
        base = pascal(`${verb} ${base}`);
      }
      taken.add(base);

      rows.push({ base, path, verb, summary: op.summary ?? "", body: Boolean(op.requestBody) });
    }
  }
  return rows;
}

// One name per component schema — `CourseOut`, `Token` — so a component that
// just holds or passes along a shape imports it by name instead of indexing
// `components["schemas"]` by hand.
export function modelTypes(spec) {
  return Object.keys(spec.components?.schemas ?? {}).sort();
}

export function renderOperations(spec) {
  const out = [
    "// GENERATED by openapi-op — `npm run codegen` rewrites this file.",
    "// A named request and response type per operation, off the spec's own",
    "// summaries: `Login` is `LoginRequest` and `LoginResponse`.",
    "//",
    "// A route that takes no body has no `…Request` — there is nothing to name.",
    "//",
    "// Plus one named type per component schema, below the operations — the",
    "// name a component reaches for when it just holds or passes along a shape",
    "// with no call site of its own.",
    "//",
    "// Type-only on purpose, so a `\"use client\"` component can import from here.",
    "// `endpoints.ts` would pull `server-only` into the browser bundle with it.",
    "",
    'import type { Req, Res } from "openapi-op";',
    // A spec with no component schemas has no named models below, and an
    // unused `components` import is an error under `noUnusedLocals`.
    modelTypes(spec).length
      ? 'import type { components, paths } from "./schema";'
      : 'import type { paths } from "./schema";',
    "",
  ];

  for (const row of operationTypes(spec)) {
    // The route is what the name does not already say, so that is the comment.
    const doc = `/** \`${row.verb.toUpperCase()} ${row.path}\`${row.summary ? ` — ${row.summary}` : ""} */`;
    const ref = `paths, "${row.path}", "${row.verb}"`;
    if (row.body) out.push(doc, `export type ${row.base}Request = Req<${ref}>;`);
    out.push(doc, `export type ${row.base}Response = Res<${ref}>;`, "");
  }

  for (const name of modelTypes(spec)) {
    out.push(`export type ${name} = components["schemas"]["${name}"];`);
  }
  return out.join("\n");
}
