// Spec -> source. Two outputs, off one spec so neither can lag the other:
//
//   endpoints.ts — the callable client, one `op()` per operation
//   api.md       — every path, verb, request and response, for reading

const VERBS = ["get", "post", "put", "patch", "delete"];

// `#/components/schemas/MemberOut` -> `MemberOut`, which is the key to look up
// in schema.ts. Inline shapes have no name, so they get their JSON type.
const name = (schema) => {
  if (!schema) return "—";
  if (schema.$ref) return `\`${schema.$ref.split("/").pop()}\``;
  if (schema.items) return `${name(schema.items)}[]`;
  if (schema.anyOf) return schema.anyOf.map(name).join(" \\| ");
  return `\`${schema.type ?? "object"}\``;
};

const json = (body) => name(body?.content?.["application/json"]?.schema);

export function operations(spec) {
  const rows = [];
  for (const [path, item] of Object.entries(spec.paths ?? {})) {
    for (const verb of VERBS) {
      const op = item[verb];
      if (!op) continue;

      const status = Object.keys(op.responses).find((c) => c.startsWith("2"));
      const params = [...(item.parameters ?? []), ...(op.parameters ?? [])];
      const query = params
        .filter((p) => p.in === "query")
        .map((p) => `${p.name}${p.required ? "" : "?"}`)
        .join(", ");

      rows.push({
        group: path.split("/").filter(Boolean)[2] ?? path,
        path,
        verb: verb.toUpperCase(),
        query: query || "—",
        req: json(op.requestBody),
        res: status === "204" ? "—" : json(op.responses[status]),
        status,
      });
    }
  }
  return rows;
}

export function renderDocs(spec) {
  const rows = operations(spec);
  const groups = [...new Set(rows.map((r) => r.group))];
  return [
    "<!-- Generated by openapi-op — `npm run codegen` rewrites this. -->",
    "",
    "# API map",
    "",
    `${spec.info?.title ?? "API"} ${spec.info?.version ?? ""} — ${rows.length} operations.`,
    'Type names are keys of `components["schemas"]` in `schema.ts`;',
    'reach them as `Schema<"MemberOut">` from `api-types.ts`.',
    "",
    ...groups.flatMap((g) => [
      `## ${g}`,
      "",
      "| Method | Path | Query | Request | → | Response |",
      "| --- | --- | --- | --- | --- | --- |",
      ...rows
        .filter((r) => r.group === g)
        .map((r) => `| ${r.verb} | \`${r.path}\` | ${r.query} | ${r.req} | ${r.status} | ${r.res} |`),
      "",
    ]),
  ].join("\n");
}

// --- endpoints.ts ---

const camel = (s) =>
  s
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((w, i) => (i ? w[0].toUpperCase() + w.slice(1).toLowerCase() : w.toLowerCase()))
    .join("");

// `List Members` in the `members` group is `members.list`, not
// `members.listMembers` — the group already said it. Only the trailing word
// goes, and only when it *is* the group, so `changeRole` under members keeps
// its noun.
function methodName(summary, group) {
  const words = summary.trim().split(/\s+/);
  const last = words.at(-1).toLowerCase().replace(/s$/, "");
  if (words.length > 1 && last === group.toLowerCase().replace(/s$/, "")) words.pop();
  return camel(words.join(" "));
}

export function endpoints(spec, { prefix = "" } = {}) {
  const groups = new Map();

  for (const [path, item] of Object.entries(spec.paths ?? {})) {
    // The generated client only speaks to routes under the prefix `api()`
    // adds — anything outside it (/healthz) is left to a direct call.
    if (!path.startsWith(`${prefix}/`)) continue;
    const group = path.slice(prefix.length + 1).split("/")[0];

    for (const verb of VERBS) {
      const operation = item[verb];
      if (!operation) continue;

      const rows = groups.get(group) ?? [];
      const status = Object.keys(operation.responses).find((c) => c.startsWith("2"));
      const res = operation.responses[status]?.content?.["application/json"]?.schema?.$ref;

      let key = methodName(operation.summary ?? `${verb} ${group}`, group);
      // A summary that collides after the group word is dropped keeps its verb.
      if (rows.some((r) => r.key === key)) key = camel(`${verb} ${key}`);

      rows.push({
        key,
        path,
        verb,
        doc: [operation.summary, operation.description].filter(Boolean).join("\n\n"),
        // A `Paginated[X]` response also gets a rows-only sibling — every
        // caller today wants `.items`, and the envelope stays one call away.
        paginated: (res ?? "").split("/").pop()?.startsWith("Paginated_") ?? false,
      });
      groups.set(group, rows);
    }
  }
  return groups;
}

const jsdoc = (text, indent) =>
  text
    ? [
        `${indent}/**`,
        ...text.split("\n").map((l) => `${indent} *${l ? ` ${l.trimEnd()}` : ""}`),
        `${indent} */`,
      ]
    : [];

export function renderEndpoints(spec, { prefix = "", client = "./api" } = {}) {
  const groups = endpoints(spec, { prefix });
  const out = [
    "// GENERATED by openapi-op — `npm run codegen` rewrites this file.",
    "// Do not edit: every name, path, verb and doc comment comes from the spec.",
    "//",
    `// Each entry is \`op(path, verb)\` from ${client}, which reads the request,`,
    "// query, path params and response type out of schema.ts.",
    "",
    `import { op } from "${client}";`,
    "",
  ];

  for (const [group, rows] of groups) {
    // A paginated op is hoisted to a const first: the `Items` sibling refers to
    // it, and a reference to the object being defined is circular.
    const hoisted = (row) => camel(`${group} ${row.key}`);
    for (const row of rows.filter((r) => r.paginated)) {
      out.push(`const ${hoisted(row)} = op("${row.path}", "${row.verb}");`);
    }

    out.push(`export const ${camel(group)} = {`);
    for (const row of rows) {
      out.push(...jsdoc(row.doc, "  "));
      out.push(
        row.paginated
          ? `  ${row.key}: ${hoisted(row)},`
          : `  ${row.key}: op("${row.path}", "${row.verb}"),`,
      );
      if (row.paginated) {
        out.push(
          `  /** \`${row.key}\`, unwrapped to the rows — the envelope carries \`total\` and \`next_offset\`. */`,
          `  ${row.key}Items: async (...args: Parameters<typeof ${hoisted(row)}>) =>`,
          `    (await ${hoisted(row)}(...args)).items,`,
        );
      }
    }
    out.push("};", "");
  }
  return out.join("\n");
}
